name: 'Terraform Run'

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
  workflow_dispatch:



jobs:
  terraform:
    name: 'Terraform Run'
    runs-on: self-hosted


    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Terraform
      run: |
          sudo yum install -y yum-utils
          sudo sed -i 's/\$releasever/9/g' /etc/yum.repos.d/hashicorp.repo
          sudo yum clean all
          sudo yum makecache
          sudo yum install terraform
      
          sudo tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
            [google-cloud-cli]
            name=Google Cloud CLI
            baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
            enabled=1
            gpgcheck=1
            repo_gpgcheck=0
            gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
            EOM
            sudo yum -y install terraform
            terraform --version




           
        
